config/routes.rb
Rails.application.routes.draw do
  resources :babies do
    member do
      get 'born'
      post 'born', to: 'babies#born_post'
    end
      resources :pools
  end
  devise_for :admins
  get 'index/index'
  get 'index/score', as: 'score'
  get 'index/privacy_policy', as: 'privacy_policy'
 
  root 'index#index'
end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :admin
  belongs_to :baby

    def updateAfterBabyBorn(baby)
        gender_points = self.gender === baby.gender ? 440 : 0
        birth_date_difference = self.determineValue(220 - (20 * (self.birth_date - baby.birth_date).to_i.abs))
        self.update_attribute(:birth_date_points, birth_date_difference)
        if self.birth_time
            birth_time_difference = self.determineValue(120 - (5 * ((self.birth_time - baby.birth_time) / 1.hour).abs))
        else
            birth_time_difference = 0
        end
        self.update_attribute(:birth_time_points, birth_time_difference)
        birth_weight_difference = self.determineValue(50 - (5 * ((self.weight - baby.weight).abs)))
        self.update_attribute(:birth_weight_points, birth_weight_difference)
        birth_length_difference = self.determineValue(50 - (5 * (((self.length - baby.length) / 0.25).abs)))
        self.update_attribute(:birth_length_points, birth_length_difference)

        total = gender_points + birth_date_difference + birth_time_difference + birth_weight_difference + birth_length_difference
        self.update_attribute(:score, total)

        return total
    end

    def setWinner
        self.update_attribute(:winner, true)
    end

    def determineValue(val)
        if val < 0
            return 0
        else
            return val.to_i.round
        end
    end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool, only: [:show, :edit, :update, :destroy]

  # GET /pools/new
  def new
    @baby = Baby.find(params[:baby_id])
    @pool = Pool.new
  end

  # POST /pools
  # POST /pools.json
  def create
    @pool = Pool.new(pool_params)
    @pool.weight = (params[:pool][:weight_lbs].to_i * 16) + params[:pool][:weight_oz].to_i
    respond_to do |format|
      if @pool.save
        format.html { redirect_to baby_path(@pool.baby_id), notice: 'Thank you for betting. Good luck!' }
        format.json { render :show, status: :created, location: @pool }
      else
        format.html { render :new }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pools/1
  # PATCH/PUT /pools/1.json
  def update
    respond_to do |format|
      if @pool.update(pool_params)
        format.html { redirect_to baby_path(@pool.baby_id), notice: 'Bet was successfully updated.' }
        format.json { render :show, status: :ok, location: @pool }
      else
        format.html { redirect_to baby_path(@pool.baby_id), notice: 'Bet was successfully updated.' }
        format.json { render json: @pool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pools/1
  # DELETE /pools/1.json
  def destroy
    @pool.destroy
    respond_to do |format|
      format.html { redirect_to baby_path(@pool.baby_id), notice: 'Bet was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pool
      @pool = Pool.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pool_params
      params.require(:pool).permit(:name, :email, :gender, :birth_date, :birth_time, :length, :weight, :admin_id, :baby_id, :paid)
    end
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/views/pools/_form.html.erb
<%= form_with(model: pool, url: baby_pools_path, method: 'post', local: true) do |form| %>
  <% if pool.errors.any? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-alert alert-dismissible fade show" role="alert">
          <h2><%= pluralize(pool.errors.count, "error") %> prohibited this bet from being saved:</h2>

          <ul>
            <% pool.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>
    <div class="form-group">
        <%= form.label :name, 'Your Name' %>
        <%= form.text_field :name, required: true, value: (current_admin.name if current_admin), class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :email, 'Your Email' %>
        <%= form.text_field :email, value: (current_admin.email if current_admin), class: "form-control" %>
    </div>
    <div class="form-group">
        <% if @baby.gender != "It's a Surprise" %>
            <%= form.hidden_field :gender, value: @baby.gender %>
        <% else %>
            <%= form.label :gender %>
            <%= form.select :gender, ['Boy', 'Girl'], {include_blank: 'Select a Gender', selected: @baby.gender}, {class: "form-control", required: true} %>
            <small class="form-text text-muted">There is a <a href="https://www.thebump.com/a/more-baby-boys-than-girls">51%</a> chance that the gender will be a boy.</small>
        <% end %>
    </div>
    <div class="form-group">
        <label for="birthDay">Birth Day</label>
        <%= form.label :birth_date, "Birth Day" %>
        <%= form.date_field :birth_date, class: "form-control", value: @baby.due_date, max: @baby.due_date + 1.month, min: @baby.due_date - 1.month, required: true %>
        <small class="form-text text-muted">The due date is <%= @baby.due_date.strftime("%B %d %Y") %>.</small>
    </div>
    <div class="form-group">
        <%= form.label :birth_time %>
        <%= form.time_field :birth_time, class: "form-control" %>
    </div>
    <div class="form-group">
        <%= form.label :length %>
        <div class="input-group mb-2">
            <%= form.number_field :length, class: "form-control", value: "20", max: "30", min: "3", step: "0.1" %>
            <div class="input-group-prepend">
                <div class="input-group-text">inches</div>
            </div>
        </div>
        <small class="form-text text-muted">The average length of a newborn is 20 inches.</small>
    </div>
    <div class="form-group">
        <%= form.label :weight %>
        <div class="row">
            <div class="col">
                <div class="input-group mb-2">
                    <%= form.number_field :weight_lbs, class: "form-control", value: "7", max: "15", min: "3" %>
                    <div class="input-group-prepend">
                        <div class="input-group-text">lbs</div>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="input-group mb-2">
                    <%= form.number_field :weight_oz, class: "form-control", value: "8", max: "15", min: "0" %>
                    <div class="input-group-prepend">
                        <div class="input-group-text">oz</div>
                    </div>
                </div>
            </div>
          </div>
        <small class="form-text text-muted">The average weight of a newborn is 7 lbs 8 oz.</small>
    </div>
    <%= form.hidden_field :baby_id, value: @baby.id %>
    <%= form.hidden_field :admin_id, value: @baby.admin_id %>
    <div class="form-group">
        <%= form.submit "Submit", class: "btn btn-success" %>
    </div>
<% end %>

app/views/pools/new.html.erb
<h1>Submit a Bet</h1>

<% if Date.today < @baby.end_date %>
    <%= render 'form', pool: @pool %>
<% else %>
    <p>This pool is closed.</p>
<% end %>