config/routes.rb
Rails.application.routes.draw do
  resources :babies do
    member do
      get 'born'
      post 'born', to: 'babies#born_post'
    end
      resources :pools
  end
  devise_for :admins
  get 'index/index'
  get 'index/score', as: 'score'
  get 'index/privacy_policy', as: 'privacy_policy'
 
  root 'index#index'
end

app/models/baby.rb
class Baby < ApplicationRecord
  belongs_to :admin
  has_many :pool, dependent: :delete_all
end

app/controllers/babies_controller.rb
class BabiesController < ApplicationController
  before_action :set_baby, only: [:show, :edit, :update, :destroy, :born, :born_post]
  helper_method :isPresent

  # GET /babies
  # GET /babies.json
  def index
    @babies = Baby.where(admin_id: current_admin.id, is_born: false)
    @completed_babies = Baby.where(admin_id: current_admin.id, is_born: true)
  end

  # GET /babies/1
  # GET /babies/1.json
  def show
    @pools = Pool.where(baby_id: @baby.id)

    @boyCount = 0
    @girlCount = 0

    lengthTotal = 0.0
    weightTotal = 0.0
    lengthCount = 0
    weightCount = 0

    @dates = []
    @times = []

    @pools.each do |p|
      if p.gender == 'girl'
        @girlCount += 1
      else
        @boyCount += 1
      end

      if isPresent(p.length)
        lengthTotal += p.length.to_f
        lengthCount += 1
      end
      if isPresent(p.weight)
        weightTotal += p.weight.to_f
        weightCount += 1
      end

      @dates << p.birth_date
      if isPresent(p.birth_time)
        @times << p.birth_time
      end
    end

    if @baby.is_born
      @winner = getBabyWinner(@baby.id)
      @pools = @pools.sort_by { |k| k.score}.reverse
    end

    if lengthCount > 0
      @lengthAverage = lengthTotal / lengthCount
    end
    if weightCount > 0
      @weightAverage = weightTotal / weightCount
    end
  end

  # GET /babies/new
  def new
    @baby = Baby.new
  end

  # GET /babies/1/edit
  def edit
  end

  # POST /babies
  # POST /babies.json
  def create
    @baby = Baby.new(baby_params)

    respond_to do |format|
      if @baby.save
        format.html { redirect_to @baby, notice: 'Baby pool was successfully created.' }
        format.json { render :show, status: :created, location: @baby }
      else
        format.html { render :new }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /babies/1
  # PATCH/PUT /babies/1.json
  def update
    respond_to do |format|

      if @baby.update(baby_params)
        format.html { redirect_to @baby, notice: 'Baby pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /babies/1
  # DELETE /babies/1.json
  def destroy
    @baby.destroy
    respond_to do |format|
      format.html { redirect_to babies_url, notice: 'Baby pool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /baby/born/1
  # GET /baby/born/1.json
  def born
    weight = ozToLbs(@baby.weight).split(' ')
    @weight_oz = weight[2]
    @weight_lbs = weight[0]
  end


  # POST /baby/born/1
  # POST /baby/born/1.json
  def born_post
    if params[:baby][:weight_lbs] && params[:baby][:weight_oz]
      @baby.weight = (params[:baby][:weight_lbs].to_i * 16) + params[:baby][:weight_oz].to_i
    end
    respond_to do |format|
      if @baby.update(baby_params)
        @pools = Pool.where(baby_id: @baby.id)
        pool_winner = {points: 0, pool: 0}
        @pools.each do |p|
          points = p.updateAfterBabyBorn(@baby)
          if points > pool_winner[:points]
            pool_winner[:points] = points
            pool_winner[:pool] = p
          end
        end

        pool_winner[:pool].setWinner

        format.html { redirect_to @baby, notice: 'Baby pool was successfully updated.' }
        format.json { render :show, status: :ok, location: @baby }
      else
        format.html { render :edit }
        format.json { render json: @baby.errors, status: :unprocessable_entity }
      end
    end
  end

  def isPresent(var)
    if defined?(var) && var.present?
      return true
    end

    return false
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_baby
      @baby = Baby.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def baby_params
      params.require(:baby).permit(:title, :due_date, :end_date, :description, :admin_id, :gender, :payment_link, :registry_link, :baby_name, :birth_date, :birth_time, :length, :weight, :is_born)
    end
    def pool_params
      params.require(:pool).permit(:score)
    end
end

app/helpers/babies_helper.rb
module BabiesHelper
end

app/views/babies/_baby_born_form.html.erb
<%= form_with(model: baby, url: born_baby_path(id: baby), method: 'post', local: true) do |form| %>
  <% if baby.errors.any? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-alert alert-dismissible fade show" role="alert">
          <h2><%= pluralize(baby.errors.count, "error") %> prohibited this pool from being saved:</h2>

          <ul>
            <% baby.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :baby_name %>
    <%= form.text_field :baby_name, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.select :gender, ['Boy', 'Girl'], {include_blank: 'Select a Gender', selected: @baby.gender}, {class: "form-control", required: true} %>
  </div>

  <div class="form-group">
      <%= form.label :birth_date, "Birth Day" %>
      <%= form.date_field :birth_date, class: "form-control", required: true %>
  </div>
  <div class="form-group">
      <%= form.label :birth_time %>
      <%= form.time_field :birth_time, class: "form-control", required: true %>
  </div>
  <div class="form-group">
      <%= form.label :length %>
      <div class="input-group mb-2">
          <%= form.number_field :length, class: "form-control", required: true, step: "0.1", min: 0 %>
          <div class="input-group-prepend">
              <div class="input-group-text">inches</div>
          </div>
      </div>
  </div>
  <div class="form-group">
      <%= form.label :weight %>
      <div class="row">
          <div class="col">
              <div class="input-group mb-2">
                  <%= form.number_field :weight_lbs, value: @weight_lbs, class: "form-control", required: true, min: 0 %>
                  <div class="input-group-prepend">
                      <div class="input-group-text">lbs</div>
                  </div>
              </div>
          </div>
          <div class="col">
              <div class="input-group mb-2">
                  <%= form.number_field :weight_oz, value: @weight_oz,  class: "form-control", required: true, min: 0 %>
                  <div class="input-group-prepend">
                      <div class="input-group-text">oz</div>
                  </div>
              </div>
          </div>
        </div>
  </div>

  <%= form.hidden_field :is_born, value: true %>
  <%= form.hidden_field :admin_id, value: current_admin.id %>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/babies/_edit_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-alert alert-dismissible fade show" role="alert">
          <h2><%= pluralize(baby.errors.count, "error") %> prohibited this pool from being saved:</h2>

          <ul>
            <% baby.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.select :gender, ['It\'s a Surprise', 'Boy', 'Girl'], {include_blank: 'Select a Gender'}, {class: "form-control", required: true} %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.date_field :due_date, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: 10 %>
  </div>

  <div class="form-group">
    <%= form.label :payment_link %>
    <%= form.url_field :payment_link, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :registry_link %>
    <%= form.url_field :registry_link, class: "form-control" %>
  </div>

    <%= form.hidden_field :admin_id, value: current_admin.id %>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
    <%= link_to 'Remove', @baby, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/babies/_form.html.erb
<%= form_with(model: baby, local: true) do |form| %>
  <% if baby.errors.any? %>
    <div class="row">
      <div class="col">
        <div class="alert alert-alert alert-dismissible fade show" role="alert">
          <h2><%= pluralize(baby.errors.count, "error") %> prohibited this pool from being saved:</h2>

          <ul>
            <% baby.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.select :gender, ['It\'s a Surprise', 'Boy', 'Girl'], {include_blank: 'Select a Gender'}, {class: "form-control", required: true} %>
  </div>

  <div class="form-group">
    <%= form.label :due_date, 'Due Date' %>
    <%= form.date_field :due_date, value: Date.today, class: "form-control", required: true %>
  </div>

  <div class="form-group">
    <%= form.label :end_date, 'End Date' %>
    <%= form.date_field :end_date, value: Date.today - 1.months, class: "form-control", required: true %>
    <small class="form-text text-muted">It is recommended to have this be a month from the due date.</small>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control", rows: 10 %>
  </div>

  <div class="form-group">
    <%= form.label :payment_link, "Payment Link" %>
    <%= form.url_field :payment_link, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :registry_link, "Registry Link" %>
    <%= form.url_field :registry_link, class: "form-control" %>
  </div>

  <%= form.hidden_field :admin_id, value: current_admin.id %>
  <%= form.hidden_field :is_born, value: false %>

  <div class="actions">
    <%= form.submit "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/babies/_show_no_winner.html.erb
<div class="row">
    <h1><%= @baby.title %></h1>
</div>

<% if current_admin && current_admin.id === @baby.admin_id %>
    <div class="row">
        <div class="col">
            <nav class="nav nav-pills nav-fill justify-content-center">
                <%= link_to 'Edit Baby Pool', edit_baby_path(@baby), class: "nav-link" %>
                <%= link_to 'Baby Was Born', born_baby_path(id: @baby), class: "nav-link" %>
            </nav>
        </div>
    </div>
<% end %>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <p><b>Due Date:</b> <%= @baby.due_date.strftime("%B %d %Y") %></p>
                <p  style='white-space:pre-wrap'><%= @baby.description %></p>
            </div>
            <div class="col-sm-4">
                    <h2>Total Bets</h2>
                    <p><%= @pools.count %></p>
                    <h2>Links</h2>
                    <p><%= social_share_button_tag("Baby Betting Pool: #{@baby.title}", desc: @baby.description) %></p>
                    <% if isPresent(@baby.payment_link) || isPresent(@baby.registry_link) %>
                        <% if isPresent(@baby.payment_link) %><p><%= link_to "Pay Here", @baby.payment_link, class: "btn btn-success" %></p><% end %>
                        <% if isPresent(@baby.registry_link) %><p><%= link_to "View Registry", @baby.registry_link, class: "btn btn-secondary" %></p><% end %>
                    <% end %>
            </div>
        </div>

    </div>
</div>

<% if @pools.count > 0 %>
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <h2>Latest Stats</h2>
            </div>
            <% if !@baby.gender %>
                <div class="row">
                    <div class="col-sm">
                    </div>
                    <div class="col-sm">
                        <h3>Gender</h3>
                        <%= pie_chart @pools.group(:gender).count, library: {
                            scales: {
                                xAxes: [
                                    {
                                        ticks: {
                                            display: false
                                        },
                                        gridLines: {
                                            display: false
                                        }
                                    }
                                ]
                            }
                        } %>
                    </div>
                    <div class="col-sm">
                    </div>
                </div>
            <% end %>
            <div class="row">
                <div class="col-sm">
                    <h3>Birth Date</h3>
                    <p><b>Latest Date</b><br><%= @dates.max.strftime("%B %d %Y") %></p>
                    <p><b>Earliest Date</b><br><%= @dates.min.strftime("%B %d %Y") %></p>
                </div>
                <% if @times.count > 0 %>
                    <div class="col-sm">
                        <h3>Birth Time</h3>
                        <p><b>Latest Time</b><br><%= @times.max.strftime("%l:%M %p") %></p>
                        <p><b>Earliest Time</b><br><%= @times.min.strftime("%l:%M %p") %></p>
                    </div>
                <% end %>
            </div>
            <div class="row">
                <% if isPresent(@lengthAverage) %>
                    <div class="col-sm">
                        <h3>Length</h3>
                        <% if isPresent(@lengthAverage) %><p><b>Average Length</b><br><%= @lengthAverage.to_f.round(2) %> lbs</p><% end %>
                    </div>
                <% end %>
                <% if isPresent(@weightAverage) %>
                    <div class="col-sm">
                        <h3>Weight</h3>
                        <% if isPresent(@weightAverage) %><p><b>Average Weight</b><br><%= ozToLbs(@weightAverage) %></p><% end %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
<% end %>

    
<% if Date.today < @baby.end_date %>
    <div class="container">
        <div class="row">
            <div class="col">
                <p><%= link_to 'Submit a Bet', new_baby_pool_path(@baby.id), class: "btn btn-primary btn-lg btn-block" %></p>
            </div>
        </div>
    </div>
<% end %>

<% if @pools.count > 0 %>
    <div class="container">
        <div class="row">
            <h2>All Bets</h2>
        </div>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Gambler</th>
                          <th>Gender</th>
                          <th>Birth Date</th>
                          <th>Birth Time</th>
                          <th>Length</th>
                          <th>Weight</th>
                        <% if current_admin && current_admin.id === @baby.admin_id %>
                          <th>Paid</th>
                          <th>Did Pay</th>
                          <th>Remove</th>
                        <% end %>

                        </tr>
                      </thead>

                      <tbody>
                        <% @pools.each do |pool| %>
                          <tr>
                            <td><%= pool.name %></td>
                            <td><%= pool.gender %></td>
                            <td><%= pool.birth_date.strftime("%B %d %Y") %></td>
                            <td><% if pool.birth_time %><%= pool.birth_time.strftime("%l:%M %p") %><% else %><% end %></td>
                            <td><% if pool.length %><%= pool.length.to_f %> inches<% else %><% end %></td>
                            <td><% if pool.weight %><%= ozToLbs(pool.weight) %><% else %><% end %></td>
                            <% if current_admin && current_admin.id === @baby.admin_id %>
                                <td><%= pool.paid ? 'Yes' : 'No' %></td>
                                <% if !pool.paid %>
                                    <%= form_for(pool, url: baby_pool_path(baby_id: @baby.id, id: pool.id), html: {id: "pool_#{pool.id}"}) do |form| %>
                                        <%= form.hidden_field :paid, value: true %>
                                        <td><%= form.submit "Paid", class: "btn btn-outline-primary" %></td>
                                    <% end %>
                                <% else %>
                                    <td></td>
                                <% end %>
                                <%= form_for(pool, url: baby_pool_path(baby_id: @baby.id, id: pool.id),  method: :delete, data: { confirm: 'Are you sure?' }, html: {id: "pool_#{pool.id}"}) do |form| %>
                                    <td>
                                        <%= button_tag type: 'submit', class: "btn btn-outline-danger" do %>
                                            <%= octicon "trash", :"aria-label" => "Remove pool" %>
                                        <% end %>
                                    </td>
                                <% end %>
                            <% end %>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/babies/_show_winner.html.erb
<div class="row">
    <h1><%= @baby.title %></h1>
</div>

<div class="row">
    <div class="container">
        <div class="alert alert-info" role="alert" style="text-align: center;">
            <p>🎉 🎊 The baby was born! <%= @baby.baby_name %> was born <%= @baby.birth_date.strftime("%B %d %Y") %> at <%= @baby.birth_time.strftime("%l:%M %p") %> weighing <%= ozToLbs(@baby.weight) %> with a length of <%= @baby.length.to_f %> inches! 🎊 🎉</p>
        </div>
    </div>
</div>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <h2>Congratulations to <%= @winner.name %></h2>
        </div>
        <div class="row">
            <h3><%= @winner.name %> Guessed:</h3>
        </div>
        <div class="row">
            <div class="col-sm">
                <h3>Gender</h3>
                <p><%= @winner.gender %></p>
            </div>
            <div class="col-sm">
                <h3>Birth Date</h3>
                <p><%= @winner.birth_date.strftime("%B %d %Y") %></p>
                <p>Off By <%= distance_of_time_in_words(@winner.birth_date, @baby.birth_date) %></p>
            </div>
            <% if @times.count > 0 %>
                <div class="col-sm">
                    <h3>Birth Time</h3>
                    <p><%= @winner.birth_time.strftime("%l:%M %p") %></p>
                    <p>Off By <%= distance_of_time_in_words(@winner.birth_time, @baby.birth_time) %></p>
                </div>
            <% end %>
            <% if isPresent(@lengthAverage) %>
                <div class="col-sm">
                    <h3>Length</h3>
                    <p><%= @winner.length.to_f.round(2) %> lbs</p>
                    <p>Off By <%= (@winner.length.to_f - @baby.length.to_f).abs.round(2) %> lbs</p>
                </div>
            <% end %>
            <% if isPresent(@weightAverage) %>
                <div class="col-sm">
                    <h3>Weight</h3>
                    <p><%= ozToLbs(@winner.weight) %></p>
                    <p>Off By <%= ozToLbs((@winner.weight - @baby.weight).abs) %></p>
                </div>
            <% end %>
        </div>
    </div>
</div>

<div class="jumbotron">
    <div class="container">
        <div class="row">
            <h2>Official Stats</h2>
        </div>
        <div class="row">
            <div class="col-sm">
                <h3>Gender</h3>
                <% if @baby.is_born %><p><b>Correct Gender</b><br><%= @baby.gender %></p><% end %>
                
            </div>
            <div class="col-sm">
                <h3>Birth Date</h3>
                <p><b>Correct Birth Date</b><br><%= @baby.birth_date.strftime("%B %d %Y") %></p>
            </div>
            <% if @times.count > 0 %>
                <div class="col-sm">
                    <h3>Birth Time</h3>
                    <p><b>Correct Birth Time</b><br><%= @baby.birth_time.strftime("%l:%M %p") %></p>
                </div>
            <% end %>
            <% if isPresent(@lengthAverage) %>
                <div class="col-sm">
                    <h3>Length</h3>
                    <p><b>Correct Length</b><br><%= @baby.length.to_f.round(2) %> lbs</p>
                </div>
            <% end %>
            <% if isPresent(@weightAverage) %>
                <div class="col-sm">
                    <h3>Weight</h3>
                    <p><b>Correct Weight</b><br><%= ozToLbs(@baby.weight) %></p>
                </div>
            <% end %>
        </div>
    </div>
</div>

<% if @pools.count > 0 %>
    <div class="container">
        <div class="row">
            <h2>All Bets</h2>
        </div>
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Gambler</th>
                          <th>Gender</th>
                          <th>Birth Date</th>
                          <th>Birth Time</th>
                          <th>Length</th>
                          <th>Weight</th>
                          <th><span data-toggle="modal" data-target="#exampleModal">Score <%= octicon "info", :"aria-label" => "Scoring Info" %></span></th>
                        <% if current_admin && current_admin.id === @baby.admin_id %>
                          <th>Paid</th>
                          <th>Did Pay</th>
                          <th>Remove</th>
                        <% end %>

                        </tr>
                      </thead>

                      <tbody>
                        <% @pools.each do |pool| %>
                          <tr>
                            <td><% if pool.winner %>🎉 <% end %><%= pool.name %></td>
                            <td><%= pool.gender %></td>
                            <td><%= pool.birth_date.strftime("%B %d %Y") %></td>
                            <td><% if pool.birth_time %><%= pool.birth_time.strftime("%l:%M %p") %><% else %><% end %></td>
                            <td><% if pool.length %><%= pool.length.to_f %> inches<% else %><% end %></td>
                            <td><% if pool.weight %><%= ozToLbs(pool.weight) %><% else %><% end %></td>
                            <td><%= pool.score %></td>
                            <% if current_admin && current_admin.id === @baby.admin_id %>
                                <td><%= pool.paid ? 'Yes' : 'No' %></td>
                                <% if !pool.paid %>
                                    <%= form_for(pool, url: baby_pool_path(baby_id: @baby.id, id: pool.id), html: {id: "pool_#{pool.id}"}) do |form| %>
                                        <%= form.hidden_field :paid, value: true %>
                                        <td><%= form.submit "Paid", class: "btn btn-outline-primary" %></td>
                                    <% end %>
                                <% else %>
                                    <td></td>
                                <% end %>
                                <%= form_for(pool, url: baby_pool_path(baby_id: @baby.id, id: pool.id),  method: :delete, data: { confirm: 'Are you sure?' }, html: {id: "pool_#{pool.id}"}) do |form| %>
                                    <td>
                                        <%= button_tag type: 'submit', class: "btn btn-outline-danger" do %>
                                            <%= octicon "trash", :"aria-label" => "Remove pool" %>
                                        <% end %>
                                    </td>
                                <% end %>
                            <% end %>
                          </tr>
                        <% end %>
                      </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">How We Score</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render 'index/score' %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/babies/baby_born.html.erb
<div class="row">
    <h1>A Baby Is Born!</h1>
</div>
<div class="row">
    <div class="col">
        <%= render 'baby_born_form', baby: @baby %>
    </div>
</div>

app/views/babies/born.html.erb
<div class="row">
    <h1>A Baby Is Born!</h1>
</div>
<div class="row">
    <div class="col">
        <%= render 'baby_born_form', baby: @baby %>
    </div>
</div>

app/views/babies/edit.html.erb
<div class="row">
    <h1>Editing "<%= @baby.title %>"</h1>
</div>
<div class="row">
    <div class="col">
        <%= render 'edit_form', baby: @baby %>
    </div>
</div>

app/views/babies/index.html.erb
<div class="row">
  <h1>My Baby Pools</h1>
</div>

<% if @babies.count > 0 %>
  <div class="row">
    <div class="row">
      <h2>Open Baby Pools</h2>
    </div>
    <div class="table-responsive">
      <table class="table">
        <thead>
          <tr>
            <th style="text-align: center;">Pool</th>
            <th style="text-align: center;">Due Date</th>
            <th style="text-align: center;">End Date</th>
            <th style="text-align: center;">Baby Was Born</th>
            <th></th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @babies.each do |baby| %>
            <tr>
              <td style="text-align: center;"><%= link_to baby.title, baby_path(baby) %></td>
              <td style="text-align: center;"><%= baby.due_date.strftime("%B %d %Y") %></td>
              <td style="text-align: center;"><%= baby.end_date.strftime("%B %d %Y") %></td>
              <td style="text-align: center;"><%= link_to '👶', born_baby_path(baby), class: "nav-link" %></td>
              <td style="text-align: center;">
                <%= link_to edit_baby_path(baby) do%>
                  <%= octicon "pencil", :"aria-label" => "Edit pool" %>
                <% end %>
              </td>
              <td style="text-align: center;">
                <%= link_to baby_path(baby), method: 'delete' do%>
                  <%= octicon "trash", :"aria-label" => "Remove pool" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
<% else %>
  <p><%= link_to "Create a New Pool", new_baby_path(current_admin) %></p>
<% end %>


<% if @completed_babies.count > 0 %>
<div class="row">
  <div class="row">
    <h2>Completed Baby Pools</h2>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th style="text-align: center;">Pool</th>
          <th style="text-align: center;">Birth Date</th>
          <th style="text-align: center;">Winner</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @completed_babies.each do |baby| %>
          <tr>
            <td style="text-align: center;"><%= link_to baby.title, baby_path(baby) %></td>
            <td style="text-align: center;"><%= baby.birth_date.strftime("%B %d %Y") %></td>
            <td style="text-align: center;"><%= getBabyWinner(baby.id).name %></td>
            <td style="text-align: center;">
              <%= link_to baby_path(baby), method: 'delete' do%>
                <%= octicon "trash", :"aria-label" => "Remove pool" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

app/views/babies/new.html.erb
<div class="row">
    <h1>Create a New Baby Pool</h1>
</div>
<div class="row">
    <div class="col">
        <%= render 'form', baby: @baby %>
    </div>
</div>

app/views/babies/show.html.erb
<% if @baby.is_born %>
    <%= render 'show_winner' %>
<% else %>
    <%= render 'show_no_winner' %>
<% end %>