config/routes.rb
Rails.application.routes.draw do
  resources :babies do
    member do
      get 'born'
      post 'born', to: 'babies#born_post'
    end
      resources :pools
  end
  devise_for :admins
  get 'index/index'
  get 'index/score', as: 'score'
  get 'index/privacy_policy', as: 'privacy_policy'
 
  root 'index#index'
end

app/views/layouts/_footer.html.erb
<nav class="navbar bottom navbar-light bg-light">
    <ul class="nav flex-column">
        <li class="nav-item">
            <%= link_to "Privacy Policy", privacy_policy_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <%= link_to "Scoring", score_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
            <a target="_blank" href="https://www.buymeacoffee.com/evanmcc" class="nav-link">Buy me a Beer</a>
        </li>
    </ul>
</nav>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Baby Pool", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if current_admin %>
            <li class="nav-item">
                <%= link_to "My Pools", babies_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Create a Pool", new_baby_path(current_admin), class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Edit My Account", edit_admin_registration_path(current_admin), class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Logout", destroy_admin_session_path, method: 'delete',  class: 'nav-link' %>
            </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "Login", new_admin_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Sign Up", new_admin_registration_path, class: 'nav-link' %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Baby Pool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'layouts/nav' %>
    </header>
    <main role="main">
      <div class="container">
          <% if notice %>
            <div class="row">
              <div class="col">
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                  <%= notice %>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              </div>
            </div>
          <% end %>
          <% if alert %>
            <div class="row">
              <div class="col">
                <div class="alert alert-alert alert-dismissible fade show" role="alert">
                  <%= alert %>
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
              </div>
            </div>
          <% end %>
          
          <div class="container">
            <%= yield %>
          </div>
      </div>
    </main>
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>